### ISSUE TITLE
Sample crashes when updating tns-core-modules to v5.1.2 ('embedderDelegate.presentNativeScriptApp' is undefined)

### ISSUE THREAD

**Issue by adrian-niculescu** [NativeScript/sample-ios-embedded#16]
The sample project no longer works with the latest NativeScript.
inspecting nsapp/package.json you can see "tns-core-modules": "^4.2.0".
To update NativeScript i ran
```
$ cd nsapp
$ tns update
> Platform ios successfully removed.
> Successfully removed plugin tns-core-modules
> Copying template files...
> Platform ios successfully added. v5.1.1
> added 2 packages from 5 contributors and audited 2 packages in 1.113s
> found 0 vulnerabilities
> 
> + tns-core-modules@5.1.2
> added 3 packages from 2 contributors and audited 5 packages in 3.21s
> found 0 vulnerabilities
> 
> Successfully installed plugin tns-core-modules.
```
after this, nsapp builds and runs successfully, but when running the native CoolApp the app crashes.
Most relevant:
```
2019-01-28 13:45:31.117606+0200 CoolApp[651:127843] JavaScript error:
2019-01-28 13:45:31.117647+0200 CoolApp[651:127843] file:///app/tns_modules/tns-core-modules/application/application.js:288:64: JS ERROR TypeError: embedderDelegate.presentNativeScriptApp is not a function. (In 'embedderDelegate.presentNativeScriptApp(controller)', 'embedderDelegate.presentNativeScriptApp' is undefined)
```

Complete stack trace:
```
2019-01-28 13:45:31.112322+0200 CoolApp[651:127843] ***** Fatal JavaScript exception - application has been terminated. *****
2019-01-28 13:45:31.112356+0200 CoolApp[651:127843] Native stack trace:
2019-01-28 13:45:31.115417+0200 CoolApp[651:127843] 1   0x1013d5194 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
1   0x1013d5194 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool, bool)
2019-01-28 13:45:31.115473+0200 CoolApp[651:127843] 2   0x10140b720 -[TNSRuntime executeModule:referredBy:]
2   0x10140b720 -[TNSRuntime executeModule:referredBy:]
2019-01-28 13:45:31.115483+0200 CoolApp[651:127843] 3   0x100a11e04 -[ViewController activateNativeScript:]
3   0x100a11e04 -[ViewController activateNativeScript:]
2019-01-28 13:45:31.115723+0200 CoolApp[651:127843] 4   0x1e439c454 <redacted>
4   0x1e439c454 <redacted>
2019-01-28 13:45:31.115847+0200 CoolApp[651:127843] 5   0x1e3e29d0c <redacted>
5   0x1e3e29d0c <redacted>
2019-01-28 13:45:31.115970+0200 CoolApp[651:127843] 6   0x1e3e2a02c <redacted>
6   0x1e3e2a02c <redacted>
2019-01-28 13:45:31.116093+0200 CoolApp[651:127843] 7   0x1e3e2902c <redacted>
7   0x1e3e2902c <redacted>
2019-01-28 13:45:31.116277+0200 CoolApp[651:127843] 8   0x1e43d5bac <redacted>
8   0x1e43d5bac <redacted>
2019-01-28 13:45:31.116463+0200 CoolApp[651:127843] 9   0x1e43d6e10 <redacted>
9   0x1e43d6e10 <redacted>
2019-01-28 13:45:31.116646+0200 CoolApp[651:127843] 10  0x1e43b610c <redacted>
10  0x1e43b610c <redacted>
2019-01-28 13:45:31.116838+0200 CoolApp[651:127843] 11  0x1e4484f68 <redacted>
11  0x1e4484f68 <redacted>
2019-01-28 13:45:31.117030+0200 CoolApp[651:127843] 12  0x1e4487960 <redacted>
12  0x1e4487960 <redacted>
2019-01-28 13:45:31.117221+0200 CoolApp[651:127843] 13  0x1e4480450 <redacted>
13  0x1e4480450 <redacted>
2019-01-28 13:45:31.117253+0200 CoolApp[651:127843] 14  0x1b715d1f0 <redacted>
14  0x1b715d1f0 <redacted>
2019-01-28 13:45:31.117275+0200 CoolApp[651:127843] 15  0x1b715d170 <redacted>
15  0x1b715d170 <redacted>
2019-01-28 13:45:31.117295+0200 CoolApp[651:127843] 16  0x1b715ca54 <redacted>
16  0x1b715ca54 <redacted>
2019-01-28 13:45:31.117315+0200 CoolApp[651:127843] 17  0x1b7157920 <redacted>
17  0x1b7157920 <redacted>
2019-01-28 13:45:31.117337+0200 CoolApp[651:127843] 18  0x1b71571f0 CFRunLoopRunSpecific
18  0x1b71571f0 CFRunLoopRunSpecific
2019-01-28 13:45:31.117351+0200 CoolApp[651:127843] 19  0x1b93d0584 GSEventRunModal
19  0x1b93d0584 GSEventRunModal
2019-01-28 13:45:31.117531+0200 CoolApp[651:127843] 20  0x1e439ad40 UIApplicationMain
20  0x1e439ad40 UIApplicationMain
2019-01-28 13:45:31.117541+0200 CoolApp[651:127843] 21  0x100a12230 main
21  0x100a12230 main
2019-01-28 13:45:31.117552+0200 CoolApp[651:127843] 22  0x1b6c16bb4 <redacted>
22  0x1b6c16bb4 <redacted>
2019-01-28 13:45:31.117570+0200 CoolApp[651:127843] JavaScript stack trace:
2019-01-28 13:45:31.117598+0200 CoolApp[651:127843] 1   start@file:///app/tns_modules/tns-core-modules/application/application.js:288:64
2   anonymous@file:///app/app.js:51:18
3   evaluate@[native code]
4   moduleEvaluation@[native code]
5   promiseReactionJob@[native code]
2019-01-28 13:45:31.117606+0200 CoolApp[651:127843] JavaScript error:
2019-01-28 13:45:31.117647+0200 CoolApp[651:127843] file:///app/tns_modules/tns-core-modules/application/application.js:288:64: JS ERROR TypeError: embedderDelegate.presentNativeScriptApp is not a function. (In 'embedderDelegate.presentNativeScriptApp(controller)', 'embedderDelegate.presentNativeScriptApp' is undefined)

file:///app/tns_modules/tns-core-modules/application/application.js:288:64: JS ERROR TypeError: embedderDelegate.presentNativeScriptApp is not a function. (In 'embedderDelegate.presentNativeScriptApp(controller)', 'embedderDelegate.presentNativeScriptApp' is undefined)
2019-01-28 13:45:31.118572+0200 CoolApp[651:127843] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: embedderDelegate.presentNativeScriptApp is not a function. (In 'embedderDelegate.presentNativeScriptApp(controller)', 'embedderDelegate.presentNativeScriptApp' is undefined)
 at 
1   start@file:///app/tns_modules/tns-core-modules/application/application.js:288:64
2   anonymous@file:///app/app.js:51:18
3   evaluate@[native code]
4   moduleEvaluation@[native code]
5   promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1b71ccec4 0x1b639da40 0x1013d5544 0x10140b720 0x100a11e04 0x1e439c454 0x1e3e29d0c 0x1e3e2a02c 0x1e3e2902c 0x1e43d5bac 0x1e43d6e10 0x1e43b610c 0x1e4484f68 0x1e4487960 0x1e4480450 0x1b715d1f0 0x1b715d170 0x1b715ca54 0x1b7157920 0x1b71571f0 0x1b93d0584 0x1e439ad40 0x100a12230 0x1b6c16bb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

```

This is strange, given that ViewController implements the "presentNativeScriptApp" method and declares itself as implementing the NativeScriptEmbedderDelegate protocol (in ViewController.h)

I tried following the steps in [HOWTO.md](https://github.com/NativeScript/sample-ios-embedded/blob/master/HOWTO.md), but I encounter the same problem with a new project also.

Versions for used tools:
```
$ tns --version
5.1.1
$ xcodebuild -version
Xcode 10.1
Build version 10B61
```
